# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    increment_build_number(xcodeproj: "MARU.xcodeproj")
    build_app(workspace: "MARU.xcworkspace", scheme: "MARU")
    upload_to_testflight
  end

	desc "Match development profile"
  lane :match_local do
    match(
      username: ENV["USERNAME"],
      type: "development",
      git_url: ENV["MATCH_GIT_URL"],
      app_identifier: "kr.maru",
      clone_branch_directly: true
    )
  end

end
