name: PR_tag

on: pull_request

jobs:
    tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
        name: commenting
        with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
            github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "@5anniversary @psychehose @@profitjean "
            })
